server:
  port: 8080

#Database
spring:
  datasource:
    url: "jdbc:mysql://127.0.0.1:3306/dak2-2024"
    username: "root"
    password: "admin@123"

#Hikari Connection Pooling
    hikari:
      connection-timeout: 20000
      minimum-idle: 5
      maximum-pool-size: 12
      idle-timeout: 300000
      max-lifetime: 1200000
      auto-commit: true

#Hibernate
  jpa:
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQLDialect"
        ddl-auto: "update"
    show-sql: "true"
    generate-ddl: "true"

#Redis
  cache:
    type: "redis"
  data:
    redis:
      cluster:
        nodes:
          - "localhost:7001"
          - "localhost:7002"
          - "localhost:7003"
          - "localhost:7004"
          - "localhost:7005"
          - "localhost:7006"

#Mail
  mail:
    host: "smtp.gmail.com"
    port: 587
    username: "mos98er@gmail.com"
    password: "tpfqmbtzvgwhfgqo"
  properties:
    mail:
      smtp:
        auth: "true"
        starttls:
          enable: "true"